name: CI

on:
  push:
    branches: ["dev", "*-dev"]
  pull_request:
    branches: ["dev", "*-dev"]
  workflow_dispatch:
    inputs:
      ref:
        description: "Git reference to build (branch, tag, or commit SHA)"
        required: false
        default: "dev"

jobs:
  build-test-multi-platform:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            build_type: Debug
            c_compiler: gcc
            cpp_compiler: g++

          - os: ubuntu-latest
            build_type: RelDebInfo
            c_compiler: gcc
            cpp_compiler: g++

          - os: ubuntu-latest
            build_type: Debug
            c_compiler: clang
            cpp_compiler: clang++

          - os: ubuntu-latest
            build_type: RelDebInfo
            c_compiler: clang
            cpp_compiler: clang++

          - os: macos-latest
            build_type: Debug
            c_compiler: clang
            cpp_compiler: clang++

          - os: macos-latest
            build_type: RelDebInfo
            c_compiler: clang
            cpp_compiler: clang++

          - os: windows-latest
            build_type: Debug
            c_compiler: cl
            cpp_compiler: cl

          - os: windows-latest
            build_type: RelDebInfo
            c_compiler: cl
            cpp_compiler: cl
    
    # NOTE: Only build on windows ... msvc does not like munit at all
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}

      - name: Set compilers
        run: |
          echo "CC=${{ matrix.c_compiler }}" >> $GITHUB_ENV
          echo "CXX=${{ matrix.cpp_compiler }}" >> $GITHUB_ENV

      - name: Maybe setup MSVC
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Maybe install make
        if: runner.os == 'Windows'
        run: choco install make

      - name: >
          Build |
          ${{ matrix.os }} |
          ${{ matrix.c_compiler }} |
          ${{ matrix.build_type }}
        run: |
          make build TESTS=1 BUILD_TYPE=${{ matrix.build_type }}
      - name: > 
          Test |
          ${{ matrix.os }} |
          ${{ matrix.c_compiler }} |
          ${{ matrix.build_type }}
        if: runner.os != 'Windows'
        run: | 
          make run-test 


  coverage:
    runs-on: ubuntu-latest
    env:
      CC: gcc
      CXX: g++

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}

      - name: Install deps
        run: sudo apt install -y lcov

      - name: Build and run coverage
        run: |
          make coverage
          ./check_coverage.sh

      - uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: coverage

  memcheck:
    runs-on: ubuntu-latest
    env:
      CC: gcc
      CXX: g++

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}

      - name: Install deps
        run: sudo apt install -y valgrind

      - name: Build tests and run with valgrind
        run: make memcheck
